# PT2 CHUNK OWNER a
TR = [
"Quem tem a chave",
"Esta cabina é uma ferramenta. Os bombeiros tomam-na com o seu interruptor. Tem uma segunda alimentação e está construída para continuar a funcionar quando a água corre pela caixa. Um passageiro não faz autorresgate nela ao premir um botão de patamar.",
"Depois do alarme, um elevador para bombeiros está à espera de…",
"Os bombeiros, sob o seu controlo.",
"Qualquer residente que consiga chegar ao botão.",
"Paletes de mercadorias.",
"A mesma área ocupada, função diferente",
"A cabina para bombeiros mais pequena tem 1100 × 1400 mm, 630 kg, porta de 800 mm — o mesmo tipo de área de um Tipo 2 acessível. O tamanho não a torna um elevador de evacuação. São a chave, a alimentação e a proteção contra a água que fazem a diferença.",
"Uma cabina do tamanho do Tipo 2 só é um elevador para bombeiros se…",
"Também está construída e comandada segundo a EN 81-72.",
"A área do piso coincide, ponto final.",
"Alguém instala um espelho maior.",
"Dois tipos de água",
"A água da mangueira na caixa é esperada, por isso a parte elétrica está protegida e o poço pode drenar. Uma cabeça de aspersor na caixa ou no espaço de máquinas é um duche sobre o controlador. Essa não é permitida.",
"Em torno de que água é concebido o elevador para bombeiros?",
"Água de combate a incêndios a entrar, não aspersores sobre o equipamento.",
"Aspersores na caixa, para arrefecer a cabina.",
"Um poço inundado de propósito.",
"A espera antiga",
"Durante anos o plano era um refúgio e uma espera. A 76 é a primeira norma europeia que permite que um elevador novo, construído de propósito, seja uma saída para pessoas que não podem usar as escadas. Não reescreve todos os elevadores de passageiros.",
"A 76 muda o plano para quem?",
"Pessoas que não podem usar as escadas, num elevador novo construído para isso.",
"Todos os elevadores de passageiros existentes a partir do próximo ano.",
"Apenas elevadores de mercadorias.",
"Não se pode fazer uma cabina viajar no tempo",
"Um elevador de 2018 foi construído antes de a 76 existir. Software e um sinal não o tornam essa norma. Pode melhorar uma cabina antiga ao abrigo das regras para elevadores existentes. Não pode alterar a data do seu nascimento.",
"Uma correção de software numa cabina de 2018 dá-lhe…",
"Uma cabina antiga melhor, não um elevador EN 81-76.",
"Um elevador de evacuação 76 completo.",
"Uma isenção da estratégia de incêndio.",
"O evento no painel de alarme",
"A 76 destina-se a um alarme de incêndio e à evacuação ordenada que a estratégia nomeia. Fica de lado perante sismo, inundação, tempestade, explosão e ataque químico. Se a própria caixa estiver a arder ou cheia de água, esta não é a saída.",
"Que evento está dentro da função da 76?",
"Um alarme de incêndio, com o patamar ainda um lugar seguro para esperar.",
"O edifício a inundar-se.",
"Um sismo.",
"O enredo mais simples",
"A Classe A é um edifício mais baixo que ainda não precisa de um elevador para bombeiros, um piso de saída, sem segunda alimentação elétrica, sem ninguém a conduzi-lo a partir de uma secretária. A altura e o equipamento decidem a classe, não o grau de incapacidade dos ocupantes.",
"Uma torre de 40 pisos que já precisa de um elevador para bombeiros é…",
"Não é uma história de Classe A.",
"Classe A se a cabina for grande.",
"Classe A porque tem um refúgio.",
"O equipamento mais completo",
"A Classe B traz uma segunda alimentação elétrica, uma cabina maior e a opção de mais de um piso de saída e de uma pessoa a conduzir de fora da cabina. Não há uma secretária remota na Classe A.",
"Quer alguém numa sala de controlo a enviar a cabina. Isso é…",
"Classe B.",
"Classe A com um cartaz.",
"Pedir emprestada a tabela da 70",
"A Classe A começa no Tipo 2: cadeira de rodas e um acompanhante. A Classe B começa no Tipo 3 ou no Tipo 4, a cabina mais comprida ou a que permite virar. A 76 não inventa uma nova tabela de dimensões. Aponta para a 70.",
"Classe A, sem maca. Cabina mínima?",
"Tipo 2.",
"Sem mínimo.",
"Duas da manhã",
"Automático significa que chama a cabina e ela leva-o ao piso de saída. Ninguém tem de estar acordado para a conduzir. Condutor e remoto precisam ambos de outra pessoa. A recolha e estacionamento é a cabina normal a desistir.",
"Qual é o comportamento do autorresgate independente?",
"A cabina vem quando a chama e vai sozinha para o piso de saída.",
"Um bombeiro pega na chave.",
"A cabina estaciona e abre no piso designado.",
"Uma secretária com pessoal",
"Remoto significa que uma pessoa fora da cabina o pode ver, falar consigo e enviar a cabina. Isso exige a Classe B, voz e vídeo, e um ser humano que esteja mesmo lá. Um telefone numa gaveta não é um modo.",
"Remoto sem ninguém na secretária é…",
"Um modo que na verdade não disponibilizou.",
"Continua a ser automático de Classe A.",
"Um elevador para bombeiros.",
"A escala",
"O assistido por condutor é uma pessoa formada na cabina, a recolher pessoas. Um hospital que tem pessoal de noite consegue fazê-lo. Um prédio de apartamentos sem pessoal acordado não consegue. O modo tem de corresponder a quem está no edifício.",
"Assistido por condutor sem uma pessoa formada de serviço é…",
"Um plano que falha quando o alarme é real.",
"O mesmo que o automático.",
"O que significa o remoto de Classe A.",
"Consegue sair do edifício?",
"EEL significa patamar de saída de evacuação: o piso onde a cabina para e se pode mesmo sair para o exterior. Um piso de que não se pode sair é apenas mais um patamar. A recolha deve apontar para uma saída real.",
"A cabina para numa cave sem percurso para o ar livre. Esse piso é…",
"Não é um patamar de saída de evacuação.",
"Um EEL válido se o sinal for verde.",
"O patamar deixou de servir",
"Suspender o serviço é o sinal «pare, esta saída já não é segura». A cabina vai para um patamar que ainda tem um percurso seguro e sai do serviço de evacuação. Não é a celebração no fim, nem são os bombeiros a tomar uma cabina 72.",
"O fumo enche a zona segura. A cabina de evacuação deve…",
"Sair do serviço de evacuação e ir para um patamar que ainda seja uma saída.",
"Continuar a abrir ali para ninguém esperar.",
"Esperar pela próxima visita LOLER.",
"Um minuto",
"Quando a alimentação muda, uma cabina de Classe B tem de estar de volta à evacuação em 60 segundos. Um gerador que «normalmente» arranca ao fim de alguns minutos fica fora dessa conta. A evacuação não faz uma pausa por um técnico.",
"A alimentação de reserva demora quatro minutos. Face à 76, isso é…",
"Demasiado lento. O limite é de 60 segundos.",
"Serve, se acabar por arrancar.",
"Um intervalo LOLER.",
"A grande distância entre portas",
"Se duas portas de patamar estiverem a mais de 7 m uma da outra, alguém preso entre elas precisa de uma porta para a caixa a meio. Átrios altos e pisos saltados são onde isto aparece. Não é uma escada em caracol dentro da caixa.",
"Portas de patamar a 9 m de distância num elevador de evacuação precisam de…",
"Uma porta intermédia de evacuação de emergência.",
"Nada, se a cabina for de Tipo 2.",
"Um cartaz em cada piso.",
"Uma pessoa que conhece a caixa",
"O alarme é uma conversa. A pessoa presa pode falar nos dois sentidos com um serviço de resgate que consegue identificar qual o elevador que chamou, e continua a funcionar quando a alimentação normal falhou. Uma campainha no poço não é isso.",
"O edifício está às escuras e alguém está na cabina. A 28 continua a exigir…",
"Comunicação de voz bidirecional com um serviço de resgate que consiga identificar o elevador.",
"Um e-mail para a gestão de instalações.",
"Uma luz e nenhuma voz.",
"A assistência precisa de voz",
"O modo com condutor e o modo remoto dependem ambos de outra pessoa. Se não o conseguirem ouvir, não o podem assistir. O remoto também precisa de vídeo. O modo automático continua a precisar do alarme para o momento em que a cabina simplesmente para.",
"Porque é que uma cabina de evacuação remota se importa com voz e vídeo?",
"A pessoa que ajuda não está na cabina consigo.",
"Serve apenas para música de fundo de hotel.",
"A EN 81-71 quer uma sirene.",
"Uma cabina antiga continua antiga",
"Um elevador de 1992 não é puxado para a frente até à 72 ou à 76. A 80 é a forma de classificar as lacunas de segurança. A 82 é a forma de melhorar o acesso onde o edifício o permitir. Fingir que é um elevador de evacuação novo é o passo desonesto.",
"Par de partida honesto para essa cabina de 1992?",
"EN 81-80 e EN 81-82.",
"EN 81-76 e EN 81-72, aplicadas para trás.",
"Deixá-lo até ser substituído, sem olhar.",
"Máquina nova, vão antigo",
"A 21 destina-se a um elevador de passageiros novo instalado num edifício existente cujo poço, espaço livre superior ou caixa não conseguem cumprir a 20. Acrescenta-se proteção para que o vão apertado continue seguro. Não é uma forma de rotular um controlador antigo como 76.",
"A EN 81-21 aparece quando…",
"O elevador novo não cabe nas folgas de um edifício antigo.",
"Quer evacuação automática num quadro de 1990.",
"Está a escrever um modelo LOLER.",
"Três maneiras, um alarme",
"A mesma campainha, três cabinas. A cabina normal estaciona e fica fora de serviço. A cabina para bombeiros espera pelos bombeiros. A cabina de evacuação, se a especificou e o patamar ainda estiver seguro, continua a trabalhar para pessoas que não podem usar as escadas.",
"Qual é a linha com a ordem certa: 73, depois 72, depois 76?",
"Estaciona. Bombeiros. Saída.",
"A 72 estaciona, a 76 é para mercadorias, a 73 é para macas.",
"Não rebaixe os bombeiros",
"Um edifício alto que precisa de um elevador para bombeiros não o pode trocar por uma cabina de evacuação de Classe A. A Classe A é o edifício mais simples. A 72 e a 76 podem ser ambas necessárias. Uma não apaga a outra.",
"Cliente: «Classe A em vez do elevador para bombeiros.» O que diz…",
"Não. Essa classe não é para um edifício que tem de ter a 72. Pode precisar de ambas.",
"Sim. A 76 substitui a 72 em todo o lado.",
"Instale o Tipo 1 e chame-lhe uso duplo.",
"Ninguém tem de estar livre",
"Autorresgate significa que a pessoa sai sem esperar por um ajudante formado. Isso é evacuação automática, não a chave dos bombeiros nem a cabina normal a estacionar sozinha. Um botão de alarme, por si só, não é uma saída.",
"Quem pode sair sem um ajudante estar livre?",
"Uma pessoa a usar o funcionamento automático da EN 81-76.",
"Uma pessoa numa cabina normal após a recolha da 73.",
"Uma pessoa à espera de que os bombeiros a levem.",
"A marca não é o dever",
"A marcação CE mostra que o elevador foi autorizado a entrar no mercado ao abrigo da Diretiva dos Elevadores. Isso não é o dever do responsável. Depois da entrega, o dever do responsável ao abrigo do LOLER, e a estratégia de incêndio, continuam a aplicar-se. A marca não o torna um elevador para bombeiros nem um elevador de evacuação.",
"Uma cabina nova tem marca CE. O LOLER…",
"Continua a aplicar-se quando as pessoas o utilizam.",
"Nunca se aplica.",
"Só se aplica se a marca faltar.",
"O plano B fica",
"A 76 não lhe permite deitar fora o refúgio e a cadeira de evacuação. A norma recusa-se a cobrir o dia em que o próprio elevador de evacuação está avariado ou indisponível. Os elevadores param. Os outros meios continuam a ser o plano.",
"O novo elevador de evacuação está fora de serviço. As pessoas que não podem usar escadas…",
"Continuam a precisar dos meios e dos refúgios que a estratégia manteve.",
"Não têm plano, porque a 76 os substituiu.",
"Têm de usar o comando dos bombeiros, por defeito.",
"Sem gerador, ainda assim uma saída",
"A Classe A não tem gerador. Se a energia falhar, a cabina tem ainda de se deslocar sozinha até ao piso de saída de evacuação para as pessoas poderem sair. Uma cabina que para entre pisos não fez isso.",
"Falha da rede numa cabina de Classe A. Ela deve…",
"Deslocar-se para o patamar de saída de evacuação.",
"Esperar na caixa por um técnico.",
"Tornar-se um elevador para bombeiros.",
"Sem porteiro",
"Uma porta de batente pede ao utilizador de cadeira de rodas que puxe, segure e recue. As portas automáticas de correr horizontais fazem esse trabalho. A utilização independente inclui a abertura, não apenas o espaço dentro da cabina.",
"Porque não uma porta de patamar de batente pesada numa cabina acessível?",
"A pessoa que precisa do elevador não pode ser a pessoa que o segura.",
"Os bombeiros não gostam do aspeto.",
"A EN 81-73 usa-as para estacionar.",
"Uma terça-feira, depois um dia mau",
"A 70 é o extra sobre a 20 para usar a cabina num dia normal: espaço, portas, comandos. A 76 é o extra para sair quando as escadas não servem. A 50 é o laboratório. A 58 e a 77 são outros trabalhos.",
"A acessibilidade de um elevador de passageiros novo, num dia normal, é…",
"O lugar onde espera",
"O patamar em frente de um elevador de evacuação tem de estar protegido do fogo e do fumo, porque é aí que alguém espera pela cabina. Um homem verde a correr num corredor comum não é isso. Os pisos que o elevador não serve podem ser isolados com portas corta-fogo ou portadas, em alternativa.",
"Uma zona segura falha quando…",
"Não consegue respirar ali enquanto espera.",
"Falta o grafismo.",
"Não é a casa das máquinas.",
"O mesmo facto, outra porta",
"Qual é a linha que é a mesma regra, contada a partir do patamar?",
]
