# PT2 CHUNK OWNER b
TR = [
"Meia-noite no 7.º piso",
"Gerente de noite",
"Um hotel de 9 pisos. Um elevador de passageiros, EN 81-20 + 70 Tipo 2, com comportamento em caso de incêndio da 73. Sem elevador 76. Um hóspede que usa cadeira de rodas está no 704.",
"O alarme de incêndio toca. Um colega sugere enviar o elevador ao 7 para ir buscar o hóspede. O que faz?",
"Chame o elevador ao 7. A rapidez importa mais do que a norma.",
"Esse elevador normal está sob a 73. Deve recolher e estacionar. Enviá-lo de volta para o edifício é pedir a uma cabina desprotegida que seja algo que não é.",
"Deixe o elevador recolher e estacionar. Inicie o plano de refúgio / assistência para o 704. Não venda o elevador normal como uma saída.",
"Certo. A 73 estaciona. O hóspede precisava de um plano de gestão (refúgio, ajuda formada, cadeira de evacuação) porque este edifício nunca comprou a 76.",
"Diga ao hóspede para usar o elevador na mesma — o Tipo 2 significa que é um elevador de evacuação.",
"O Tipo 2 é uma dimensão de acessibilidade, não um modo de evacuação. A 70 é entrar numa terça-feira. A 76 é sair na noite má.",
"No balanço, o proprietário pergunta se podem «ligar a EN 81-76» no controlador neste trimestre.",
"Sim — a 76 é uma opção de software em qualquer cabina de Tipo 2.",
"A 76 é equipamento adicional, patamares protegidos, comportamento da alimentação, sinalização e um elevador novo. Não é uma opção.",
"Não. A 76 é para elevadores novos com proteção do lado do edifício. Melhore o plano de assistência agora; especifique a 76 quando o elevador for substituído.",
"Honesto. Pode treinar a equipa da noite amanhã. Não pode desejar um elevador de evacuação de 2025 para dentro de um controlador 73.",
"A maioria dos edifícios em que entra esta noite ainda são edifícios 73. A gentileza é um plano ensaiado, não uma fantasia sobre a cabina.",
"A substituição na reunião",
"Consultor de acessibilidade",
"Um edifício de escritórios de 15 pisos. A estratégia de incêndio já exige um elevador para bombeiros. O empreiteiro de elevadores oferece «uma cabina de dupla função, Classe A 76, mais barata do que 72+76».",
"Classe A em vez de um elevador para bombeiros. A sua nota para o engenheiro de incêndio?",
"Aceitar — a 76 é mais recente, por isso substitui a 72.",
"A 76 não substitui a 72. A Classe A não se destina a locais onde é exigido um elevador para bombeiros.",
"Rejeite a troca. A 72 é a ferramenta dos bombeiros. A 76 é a saída dos civis. Esta altura provavelmente precisa da 72; a 76 seria extra, e não de Classe A.",
"É a reunião para a qual foi contratado. Complementares, não sabores.",
"Aceite a Classe A se a pintarem de vermelho.",
"A cor não é uma norma.",
"Voltam com a Classe B 76 mais uma cabina 72 separada. 76 assistida remotamente, sala de controlo com pessoal das 08:00–18:00.",
"Pergunte o que acontece às 18:01. Se o edifício estiver ocupado de noite, o automático ou uma escala real fora de horas tem de estar na estratégia.",
"O remoto é uma pessoa. As pessoas vão para casa. O automático é o único modo independente. Escreva os horários na estratégia de incêndio ou mude o modo.",
"O horário de expediente chega para qualquer escritório.",
"Pessoal da limpeza, engenheiros até tarde, obras noturnas — há sempre alguém num escritório de 15 pisos.",
"O erro caro é comprar uma cabina para dois trabalhos que ela não consegue cumprir. O erro barato é um modo que ninguém está acordado para executar.",
"Quem está a conduzir",
"Responsável de instalações, lar",
"Lar novo de três pisos. Não é exigido elevador para bombeiros. Um nível de saída. Gerador fora do orçamento. Residentes que não podem usar escadas em todos os pisos.",
"Classe e alimentação?",
"A Classe A está em cima da mesa: um EEL, sem gatilho de elevador para bombeiros, sem alimentação secundária — mas só se o resgate automático até ao EEL em caso de falha da rede for real.",
"Esse é o quadrado da Classe A. O «se» é o trabalho todo: resgate até ao piso de saída quando as luzes se apagam.",
"Classe B, porque os lares precisam sempre de vídeo remoto.",
"Podem escolher B, mas não é imposto pelo rótulo de ocupação. O remoto impõe B. Um edifício com pessoal pode preferir assistido por condutor em A ou B.",
"São duas pessoas de serviço à noite. O arquiteto prefere apenas o assistido por condutor.",
"Apenas assistido por condutor significa que essas duas pessoas não podem também combater um incêndio e transportar alguém. Negocie o automático também, ou prove o exercício com números.",
"É exigido pelo menos um modo; é permitido mais do que um. O automático é o único modo independente. Num lar, o pessoal já está ocupado.",
"Dois funcionários chegam para conduzir todos os residentes para fora numa só cabina.",
"Faça as contas: tamanho da cabina, número de residentes, tempo, um condutor ocupado. O automático existe porque esta fantasia falha.",
"A Classe A pode ser honesta aqui. A escolha do modo é uma escolha de pessoal. Escreva-a como um número de pessoas, não como um nome de produto.",
"A caixa do edifício classificado",
"Paços do concelho de 1890, elevador hidráulico de 1998, sem alarme bidirecional, porta de patamar de batente de 800 mm, último exame aprofundado há 11 meses.",
"Primeira chamada telefónica?",
"Encomende a conversão para a EN 81-76.",
"Década errada, norma errada, e está em atraso no LOLER.",
"Marque hoje o exame aprofundado em atraso. Em paralelo, comece um levantamento 80/82: alarme, portas, acesso. A 76 só quando substituir.",
"Primeiro o diário. Depois os perigos classificados. Depois uma especificação de substituição que possa mesmo incluir a 76.",
"Ponha uma cadeira de refúgio no átrio e esqueça o elevador.",
"Os meios ajudam. Não fecham um alarme em falta nem um exame atrasado.",
"Um vereador quer o Tipo 1 «porque é existente» na substituição.",
"O Tipo 1 só se aplica quando o edifício realmente não consegue ter o Tipo 2. Meça a caixa. Os edifícios públicos devem lutar pelo Tipo 2 ou 3.",
"O Tipo 1 em edifício existente é um argumento de constrangimento, não uma preferência. A 21 pode ajudar uma cabina nova a entrar numa caixa antiga sem encolher as pessoas.",
"O Tipo 1 serve para edifícios cívicos.",
"Um utilizador de cadeira de rodas que vai a uma reunião não devia ter de deixar o acompanhante no átrio.",
"Os edifícios antigos são 80, 82, 21, LOLER — e só depois uma conversa nova de 20+70+76. A sequência é a competência.",
"Água no quatro",
"Engenheiro de elevadores de prevenção",
"Um elevador para bombeiros 72 numa torre. Incêndio no 4. Bombeiros a usar a cabina. Relatos de água na caixa.",
"O gestor de instalações quer o elevador isolado «porque água e eletricidade».",
"Isole de imediato — qualquer água significa parar.",
"Um elevador 72 está concebido para água de combate a incêndios. Isolá-lo sem os bombeiros o pedirem pode retirar-lhes a sua ferramenta.",
"Não isole por conta própria. A 72 pressupõe água de mangueira. Fale com o comandante do incidente. Vigie o nível do poço e as avarias; eles decidem se a ferramenta ainda é deles.",
"É o médico da máquina, não o comandante do incidente. Os graus IP da 72 e a drenagem existem para esta hora.",
"72 sem gestão da água é um folheto. 72 com água na caixa é uma terça-feira.",
"Dois cartazes, um átrio",
"Gestor do edifício",
"Núcleo misto: um elevador de passageiros 73, um automático 76 de Classe B, um 72. Os inquilinos continuam a apanhar a cabina errada nos exercícios.",
"Corrija o átrio.",
"Um cartaz genérico «elevadores OK em caso de incêndio» sobre as três portas.",
"Isso mete as pessoas na cabina 73, que vai estacionar, e na cabina 72, que não é deles.",
"Três histórias diferentes: a 73 mantém a mensagem antiga de «não utilizar»; a 76 recebe o sinal de elevador de evacuação (pelo menos 40 × 40 mm) e voz; a 72 está marcada para os bombeiros. Ensaie-o.",
"A sinalização é um controlo. A 76 até dimensiona o pictograma. A formação é o resto do controlo.",
"Se o patamar não disser a verdade, a norma nunca chega à pessoa para quem foi escrita.",
"[s.id, s]), ) as Record",
"Notas de campo da Diretiva dos Elevadores",
"Os regulamentos da UE para um elevador novo, em linguagem de patamar. Não substituem a Diretiva.",
"Apresentação do elevador de evacuação",
"Classe A e Classe B, os três modos, e porque é que um elevador para bombeiros é uma cabina diferente.",
"Marcador automático do elevador",
"O alarme EN 81-28 que um passageiro preso utiliza. Não o telefone dos bombeiros.",
"Operador de porta motorizada",
"Portas de correr motorizadas para uma cabina acessível. Apenas listagem.",
"Comando de resgate de emergência",
"O comando que um assistente usa para conduzir a cabina a partir do interior do quadro de comando do elevador.",
"Livro de registo de exames",
"Um registo em papel para o exame aprofundado semestral. O dever continua a ser do proprietário.",
"A família EN 81",
"Que parte da caixa é que cada norma cobre de facto.",
"Quem fica responsável",
"Diretiva, LOLER, PUWER — as pessoas, não o metal.",
"O elevador de passageiros de base",
"A cabina, a caixa, as portas — aquilo de que parte todo o elevador novo.",
"Entrar de forma independente",
"Tipos de cabina, portas, botões que um utilizador de cadeira de rodas consegue mesmo usar.",
"Elevadores normais num incêndio",
"Porque é que um elevador normal se estaciona e se recusa a ajudar.",
"Elevadores para bombeiros",
"O elevador com que os bombeiros sobem, não aquele em que desce.",
"Porque é que a 76 existe",
"Autorresgate para pessoas que não podem usar as escadas.",
"Classe A e Classe B",
"Edifício simples contra edifício complexo — escolha a cabina certa.",
"Três formas de sair",
"Automático, assistido por condutor, assistido remotamente.",
"EEL, alimentação, água, portas",
"O edifício tem de fazer a sua parte, não apenas o elevador.",
"O alarme na cabina",
"Conversa nos dois sentidos quando alguém está preso — não uma campainha que ninguém ouve.",
"Elevadores antigos, deveres novos",
"Não pode fingir que uma cabina dos anos 1980 é uma cabina de 2025. Classifique os perigos.",
"72, 73 e 76 em conjunto",
"Que elevador faz o quê quando o alarme toca.",
"[s.id, s])) as Record",
"Elevador de passageiros",
"EN 81-20 · a cabina por defeito",
"Elevador de passageiros normal vazio, com as portas abertas para um patamar",
"Escritórios, hotéis, apartamentos — a cabina em que as pessoas andam todos os dias.",
"Esta é a máquina de base. Tudo o resto é 20 mais extras. Se a especificação estiver em silêncio, é esta a cabina que obtém — e num incêndio ela estaciona.",
"Elevador de passageiros de tração elétrica segundo a EN 81-20 e a EN 81-50, com marcação CE ao abrigo da Diretiva dos Elevadores, com alarme EN 81-28, carga nominal de 630 kg / 8 pessoas, 1.0 m/s, cabina de 1100 × 1400 mm, portas de abertura lateral de dois painéis com vão livre de 900 mm.",
"Nomeie a EN 81-20 e a 50, não «EN 81».",
"Ponha o alarme na EN 81-28, não num intercomunicador de reserva.",
"Diga o que faz num incêndio — se não disser nada, estaciona (73).",
"Não escreva «totalmente conforme com a EN 81».",
"Não trate a declaração de conformidade como o diário LOLER.",
"Carga nominal",
"630 kg (8 pessoas) ou 1000 kg (13 pessoas)",
"A carga nominal é a carga que o elevador está concebido para transportar, em quilogramas, usada no dimensionamento da cabina, dos cabos, do para-quedas e da máquina. A capacidade em pessoas deriva da carga nominal.",
"630 kg é o escritório e o apartamento do dia a dia no Reino Unido. 1000 kg se quiser uma cadeira de rodas, um carrinho de bebé e uma mala sem discussão. Escreva os quilogramas. «8 pessoas» sozinho é descuidado.",
"Velocidade nominal",
"1.0 m/s baixa altura · 1.6 m/s média altura",
"A velocidade nominal é a velocidade da cabina em metros por segundo para a qual o elevador foi construído. Os componentes de segurança, os amortecedores e o espaço livre superior são escolhidos a partir dessa velocidade.",
"Um metro por segundo é uns calmos cinco ou seis pisos. 1.6 é a média altura habitual. Mais rápido significa um poço mais fundo, mais espaço livre superior e um para-quedas diferente. Não copie uma velocidade de um folheto para uma caixa diferente.",
"Dimensão da cabina",
"1100 mm de largura × 1400 mm de profundidade × 2200 mm de altura",
"A EN 81-20 define a construção e a segurança da cabina. As dimensões de cabina de acessibilidade estão na EN 81-70. A altura interior é habitualmente especificada em 2200 mm para cabinas novas de passageiros.",
"A largura é a parede com as portas. A profundidade é até onde se entra a pé. 1100 por 1400 é a cabina de cadeira de rodas de Tipo 2. Se deixar a dimensão em branco, pode obter um armário.",
"900 mm de vão livre, abertura lateral de dois painéis, 2100 mm de altura",
"As portas de patamar e de cabina devem proteger a caixa. A resistência ao fogo das portas de patamar é especificada à parte quando a estratégia de incêndio o exige (muitas vezes classificações E / EW ao abrigo da EN 81-58).",
"900 mm de vão livre é uma porta para cadeira de rodas. A abertura central parece grandiosa; a abertura lateral muitas vezes cabe numa caixa apertada. A classificação de resistência ao fogo da porta de patamar é uma linha da estratégia de incêndio, não uma linha de porta bonita.",
"Tração sem redutor MRL, ou tração com casa das máquinas",
"A EN 81-20 abrange elevadores de passageiros de tração elétrica e hidráulicos. A configuração sem casa das máquinas (MRL) coloca a máquina na caixa. O hidráulico é uma conversa diferente sobre o curso e o óleo.",
"A maioria das cabinas novas de passageiros no Reino Unido é de tração sem redutor MRL. Uma casa das máquinas continua a ser honesta numa caixa funda ou rápida. O hidráulico é para cursos curtos. Nomeie o acionamento para que o poço e o espaço livre superior coincidam.",
"Poço e espaço livre superior",
"Poço ~1.0–1.4 m · o espaço livre superior depende da velocidade",
"Os espaços de refúgio, os amortecedores e o espaço livre superior calculam-se a partir da velocidade nominal e do para-quedas. Poço ou espaço livre superior reduzidos são EN 81-21, não um aperto de mão.",
"O buraco em baixo e o vazio em cima são espaços de segurança, não sobras do edifício. Se o arquiteto já os roubou, está na 81-21 — diga-o.",
"EN 81-28 bidirecional, resposta 24 horas",
"A EN 81-28 é o alarme remoto em elevadores de passageiros e de mercadorias com pessoas. O sistema deve estabelecer uma ligação de voz bidirecional com um serviço de 24 horas.",
"Um botão que faz tocar um telefone que ninguém atende não é um alarme. A 28 significa que alguém atende, de dia e de noite, e consegue falar com a pessoa na cabina.",
"400 V trifásico; resgate a partir do patamar em caso de falha da rede",
"O elevador deve permanecer seguro em caso de falta de alimentação. O resgate automático até ao piso mais próximo é habitual em cabinas de passageiros. Os elevadores de evacuação e para bombeiros precisam de uma alimentação secundária especificada.",
"Uma cabina normal de passageiros pode ir lentamente até ao piso seguinte e abrir quando a energia falha. Isso não é um elevador de evacuação. Se as pessoas que não podem usar escadas ainda tiverem de sair, precisa da 76 e de uma segunda alimentação a sério.",
"Elevador de passageiros acessível",
"EN 81-70 · entrar sem complicações",
"Elevador de passageiros vazio, dimensionado para utilização independente em cadeira de rodas",
"Qualquer cabina pública ou de local de trabalho em que um utilizador de cadeira de rodas tenha de poder andar sozinho.",
"A 70 é a 20 com as dimensões, os botões e a voz que permitem a uma pessoa entrar sem ajuda. A Parte M dos Regulamentos da Construção é a razão pela qual o arquiteto se importa.",
"Elevador de passageiros segundo a BS EN 81-20 e a EN 81-70 Tipo 2: carga nominal ≥ 630 kg, cabina 1100 × 1400 mm, portas com vão livre de 900 mm, comandos a duas alturas, anúncio por voz, alarme acessível, acabamentos de contraste, corrimão na parede lateral da cabina.",
"Nomeie o tipo da 70 (1, 2, 3 ou 4) — o Tipo 2 é a cabina de cadeira de rodas por defeito no Reino Unido.",
"Botões a duas alturas e um piso em que se possa virar.",
"Voz e indicadores de piso visíveis, não apenas um toque.",
"Não chame a uma cabina de Tipo 1 de 450 kg «acessível a cadeira de rodas» num edifício público.",
"Não confunda a 70 (acesso do dia a dia) com a 76 (sair num incêndio).",
"Cabina de Tipo 2 (por defeito no Reino Unido)",
]
