# PT2 CHUNK OWNER c
TR = [
"≥ 630 kg · 1100 × 1400 mm · porta de 900 mm",
"O Tipo 2 da EN 81-70 destina-se a um utilizador de cadeira de rodas com uma pessoa acompanhante. Cabina mínima de 1100 mm de largura por 1400 mm de profundidade, carga nominal de 630 kg, vão livre da porta de 900 mm.",
"É esta a cabina que especifica para um patamar público. Uma cadeira de rodas vira, alguém pode ficar ao lado, e a porta tem uns 900 mm a sério.",
"Cabina de Tipo 1",
"450 kg · 1000 × 1250 mm · porta de 800 mm",
"O Tipo 1 é a cabina 70 mais pequena: 450 kg, 1000 × 1250 mm, porta de 800 mm. É um único utilizador de cadeira de rodas, apertado.",
"Uma caixa residencial pequena, não um hospital. Se a estratégia de incêndio ou a Parte M esperam uma cadeira de rodas e um ajudante, o Tipo 1 é a opção errada.",
"Tipo 3 / maca",
"1275 kg · 1400 × 1600 mm · porta de 1100 mm",
"O Tipo 3 é para um utilizador de cadeira de rodas com várias pessoas acompanhantes; 1275 kg, 1400 × 1600 mm, porta de 1100 mm. O uso de maca é uma conversa à parte, e maior.",
"Saúde, estádios, qualquer sítio onde uma multidão e uma cadeira partilham a cabina. Escreva Tipo 3 se for esse o enredo — não espere que um Tipo 2 estique.",
"Duas alturas ~900 e 1100 mm; em relevo, contraste, braille conforme especificado",
"A EN 81-70 exige que os dispositivos de comando sejam alcançáveis a partir de uma posição sentada, com contraste tátil e visual. Uma segunda fila de botões é a forma habitual de servir utilizadores de pé e sentados.",
"Botões que um utilizador de cadeira de rodas consiga mesmo premir. Não um único COP alto «porque fica mais limpo».",
"Corrimão e espelho",
"Corrimão na parede lateral; espelho na parede do fundo de um Tipo 2",
"É previsto um corrimão na cabina. Um espelho na parede do fundo de uma cabina de Tipo 2 ajuda um utilizador de cadeira de rodas a sair em marcha-atrás.",
"O corrimão é para o equilíbrio. O espelho é para não recuar contra uma porta que não vê. Ambos são 70, não decoração.",
"Tempo de permanência",
"As portas ficam abertas o tempo suficiente para entrar sem pressa",
"Os tempos de permanência das portas na 70 são mais longos do que uma especificação de escritório para se atravessar a correr, para que um utilizador lento não seja atingido pelas portas.",
"Se as portas morderem, especificou uma cabina de hora de ponta, não uma acessível. Escreva o tempo de permanência.",
"Elevador para bombeiros",
"EN 81-72 · a ferramenta dos bombeiros",
"Bombeiro com equipamento de proteção dentro de um elevador para bombeiros, com um painel de chave e o piso molhado",
"Edifícios cuja estratégia de incêndio dá aos bombeiros um elevador só deles.",
"Elevador para bombeiros segundo a BS EN 81-20 e a EN 81-72: carga nominal ≥ 630 kg (preferir 1000 kg), velocidade nominal ≥ 1.0 m/s, cabina a servir o patamar mais afastado em 60 s, alimentação secundária, portas de patamar resistentes ao fogo, equipamento elétrico protegido contra a água, comunicação dos bombeiros, átrio de combate a incêndios conforme a estratégia de incêndio.",
"Um átrio de combate a incêndios — o elevador não é um 72 se abrir para um corredor normal.",
"Alimentação secundária e proteção contra a água nomeadas, não implícitas.",
"A estratégia de incêndio tem mesmo de exigir a 72. Altura e risco, não um folheto.",
"Não diga a um utilizador de cadeira de rodas que esta é a sua saída.",
"Não omita o átrio e mesmo assim lhe chame 72.",
"Carga nominal e dimensão",
"≥ 630 kg; 1000 kg preferível · 1100 × 1400 mm ou maior",
"A EN 81-72 fixa uma dimensão e uma carga mínimas da cabina para que os bombeiros, o equipamento e uma pessoa resgatada possam viajar. A orientação nacional de incêndio prefere muitas vezes uma cabina de 1000 kg / apta para maca em edifícios mais altos.",
"Dois bombeiros, uma mangueira e alguém numa cadeira. 630 kg é o mínimo. 1000 kg é o que a maioria das estratégias de incêndio do Reino Unido quer de facto.",
"Velocidade e tempo",
"≥ 1.0 m/s · piso mais afastado em cerca de 60 segundos",
"O elevador deve ser capaz de alcançar o patamar mais afastado a partir do nível de acesso dos bombeiros dentro de um tempo especificado, habitualmente 60 s na prática do Reino Unido, o que determina a velocidade nominal.",
"Os bombeiros não vão esperar por uma cabina residencial de 0.6 m/s. Escreva a velocidade a partir do patamar mais alto, não a partir de um catálogo.",
"Comando dos bombeiros",
"Interruptor dos bombeiros no nível de acesso; comando de incêndio na cabina",
"Um interruptor dos bombeiros no nível de acesso dos bombeiros coloca o elevador em serviço de bombeiros. Os comandos na cabina passam então a pertencer aos bombeiros.",
"Uma chave ou um interruptor no piso dos bombeiros. Depois disso, a cabina ignora as chamadas normais. Os residentes não a conduzem.",
"Alimentação secundária",
"Alimentação secundária para o elevador, a iluminação e a comunicação",
"Uma alimentação elétrica secundária deve manter o elevador para bombeiros disponível. A comutação é automática. A alimentação é dimensionada para a cabina 72, não para uma esperança.",
"Quando a rede falha, esta cabina ainda tem de funcionar para os bombeiros. Uma lanterna na cabina não é uma alimentação.",
"Parte elétrica com grau IP; drenagem na caixa / átrio conforme o projeto",
"O equipamento elétrico na caixa e na cabina deve resistir à água do combate a incêndios. A drenagem e os graus IP fazem parte do pacote 72.",
"O átrio vai estar molhado. Se o controlador ficar numa poça e morrer, os bombeiros ficam com uma cabina às escuras. Escreva a água, não apenas «72».",
"Intercomunicador dos bombeiros, da cabina para o nível de acesso dos bombeiros",
"É exigido um sistema de comunicação entre a cabina e o nível de acesso dos bombeiros. É separado do alarme EN 81-28, que é o telefone do passageiro preso para um serviço de resgate.",
"O oficial à porta da frente fala com a equipa na cabina. Essa é a linha dos bombeiros. A EN 81-28 é a outra: um passageiro prime-a quando está preso, e uma pessoa atende.",
"Átrio de combate a incêndios protegido em cada patamar 72",
"O elevador é usado com átrios de combate a incêndios definidos na estratégia de incêndio e na Parte B dos Regulamentos da Construção. A EN 81-72 é o elevador; o átrio é o edifício.",
"Sem átrio, sem elevador para bombeiros. A norma não pode inventar uma sala protegida que o arquiteto esqueceu.",
"Elevador de evacuação · Classe A",
"EN 81-76 Classe A · uma saída",
"Pessoa em cadeira de rodas dentro de um elevador de evacuação com um piso amplo e desimpedido",
"Edifícios novos com um único nível de saída de evacuação, onde as pessoas que não podem usar escadas continuam a precisar de um elevador.",
"A Classe A é a cabina 76 mais simples: um piso de saída, automático ou assistido por condutor, construída para que um utilizador de cadeira de rodas possa sair quando as escadas são a ferramenta errada.",
"Elevador de evacuação segundo a BS EN 81-20, a EN 81-70 Tipo 2 e a EN 81-76 Classe A: nível único de saída de evacuação, modo de evacuação automático, alimentação independente / secundária durante o tempo especificado, equipamento elétrico protegido contra a água, comandos a duas alturas, cabina de 630 kg / 1100 × 1400 mm, portas de 900 mm, interface com o alarme de incêndio do edifício, complementar a qualquer elevador EN 81-72 — não um substituto.",
"Nomeie a Classe A e o nível único de saída de evacuação.",
"Alimentação independente durante o tempo de que a estratégia de incêndio precisa de facto.",
"Um plano B humano se a cabina se perder.",
"Não use um elevador para bombeiros 72 como a cabina 76.",
"Não especifique a Classe A num edifício com vários pisos de saída — isso é Classe B.",
"Classe A — um nível de saída de evacuação",
"A EN 81-76 Classe A aplica-se onde há um único nível de saída de evacuação. O funcionamento pode ser automático ou assistido por condutor, conforme o conceito de evacuação do edifício.",
"Todos os que não podem usar as escadas tentam chegar ao mesmo piso de saída. Se tiver dois ou mais patamares de «saia aqui», não está na Classe A.",
"Tipo 2: 630 kg · 1100 × 1400 mm · porta de 900 mm",
"A cabina do elevador de evacuação deve acomodar um utilizador de cadeira de rodas. As dimensões do Tipo 2 da EN 81-70 são a especificação habitual no Reino Unido, com comandos a duas alturas.",
"A mesma planta de uma cabina acessível decente — porque a pessoa que sai num incêndio é a mesma pessoa que chegou esta manhã.",
"Evacuação automática; assistida por condutor se o edifício tiver pessoal",
"O modo automático proporciona autorresgate independente. O assistido por condutor precisa de uma pessoa formada. O conceito escreve-se na estratégia de incêndio, não se escolhe na entrega.",
"Noites sem pessoal precisam do automático. Um hotel com pessoal noturno pode pôr um condutor na cabina. Escreva qual, e quem está na escala.",
"Alimentação secundária / independente; duração especificada",
"A EN 81-76 exige que o elevador permaneça disponível em caso de perda da alimentação primária, durante um tempo retirado da estratégia de incêndio (muitas vezes 30, 60 ou 120 minutos na prática do Reino Unido).",
"A cabina que «continua a funcionar» precisa de eletricidade que continue a funcionar. Nomeie os minutos. Uma UPS que morre ao minuto oito é uma armadilha.",
"Interface de alarme",
"O sinal de alarme de incêndio põe a cabina em modo de evacuação",
"O elevador deve fazer interface com o sistema de deteção e alarme de incêndio do edifício, para entrar no modo de evacuação previsto em vez da recolha e estacionamento normal da 73.",
"Se o alarme só lhe disser para estacionar, especificou a 73 com botões mais bonitos. O fio até ao painel de incêndio é o fio da 76.",
"Água e portas",
"Parte elétrica protegida; portas que continuam a funcionar na estratégia",
"O equipamento elétrico deve resistir às condições de água previstas na estratégia. O funcionamento das portas tem de permanecer disponível para a utilização em evacuação.",
"Aspersores e água de combate a incêndios vão estar na caixa. As cabinas 76 são construídas a saber disso. Escreva-o, ou o primeiro alarme molhado é a última viagem.",
"Elevador de evacuação · Classe B",
"EN 81-76 Classe B · várias saídas",
"Pessoa em cadeira de rodas dentro de um elevador de evacuação especificado para mais de um piso de saída",
"Enredos complexos: vários pisos de saída, evacuação assistida remotamente, uma sala de controlo.",
"A Classe B é a 76 para um edifício que não é uma pilha simples. Mais níveis de saída, condução remota opcional e uma pessoa que consegue ver e falar com a cabina.",
"Elevador de evacuação segundo a BS EN 81-20, a EN 81-70 Tipo 2 e a EN 81-76 Classe B: vários níveis de saída de evacuação, modos assistido remotamente e/ou automático conforme a estratégia de incêndio, CCTV e voz bidirecional para um posto de controlo ocupado sempre que o edifício estiver ocupado, alimentação independente durante o tempo especificado, proteção contra a água, comandos a duas alturas, complementar à EN 81-72.",
"Liste todos os níveis de saída de evacuação.",
"Se for assistido remotamente: uma pessoa, vídeo e voz em cada hora de ocupação.",
"A mesma honestidade de alimentação, água e dimensão de cabina que a Classe A.",
"Não especifique assistido remotamente e depois deixe a secretária vazia de noite.",
"Não trate a Classe B como uma opção de software num controlador de Classe A.",
"Classe B — mais de um nível de saída de evacuação",
"A EN 81-76 Classe B abrange edifícios com mais de um nível de saída de evacuação e modos de funcionamento adicionais, incluindo a evacuação assistida remotamente.",
"As pessoas saem no rés do chão, num pódio, numa ponte. A cabina tem de saber qual o patamar que é uma saída real esta noite.",
"Condutor na sala de controlo, com vídeo e voz",
"O funcionamento assistido remotamente exige uma pessoa formada num posto de controlo, com comunicação visual e por voz, disponível sempre que a evacuação possa ser necessária.",
"Alguém que consiga ver o interior da cabina e falar, e que esteja mesmo lá. Um monitor às escuras às 2 da manhã não é Classe B.",
"O automático continua a ser exigido",
"Modo automático como recurso quando a secretária está vazia",
"Quando o edifício pode estar ocupado sem o operador remoto, o modo de evacuação automático continua a ser o caminho de autorresgate independente.",
"Se a sala de controlo sair do turno, a cabina tem ainda de saber levar sozinha um utilizador de cadeira de rodas até uma saída.",
"Alimentação, água, cabina",
"Como a Classe A, mais o percurso extra de comando",
"A alimentação secundária, a proteção contra a água e as dimensões da cabina acessível mantêm-se. A Classe B acrescenta comando e comunicação, não abandona a física da Classe A.",
"Uma secretária esperta não desculpa uma cabina pequena nem um gerador morto. O metal continua a ser uma cabina 76.",
"As chamadas de evacuação ficam com a cabina; as chamadas normais caem",
"Em modo de evacuação o elevador ignora as chamadas normais de patamar e serve o conceito de evacuação, incluindo os níveis de saída atribuídos.",
"Ninguém que «só vai ao ginásio» fica com a cabina enquanto alguém tenta sair de um piso em incêndio.",
"Elevador existente",
"EN 81-80 · 82 · LOLER · já na caixa",
"Casa das máquinas de elevador preparada para um exame aprofundado",
"Responsáveis e empreiteiros perante uma cabina que já está na caixa.",
"Não se especifica a 76 sobre metal antigo. Classifica-se o que pode matar alguém, mantém-se o diário LOLER e escreve-se um plano de assistência real até a cabina ser substituída.",
"Modernização do elevador de passageiros existente face a uma classificação de riscos documentada da EN 81-80 e a uma auditoria de acessibilidade da EN 81-82. Manter o exame aprofundado LOLER com intervalos de seis meses. Não alegar EN 81-76, EN 81-72 ou «equivalente a cabina nova» salvo se a substituição for um elevador novo ao abrigo dos Regulamentos dos Elevadores.",
"Primeiro o diário LOLER — tipicamente de seis em seis meses para elevadores que transportam pessoas.",
"Uma classificação 80 com nomes e datas, não uma impressão.",
"Um plano escrito para quem não pode usar as escadas num incêndio.",
"Não cole um autocolante 76 numa cabina anterior a 2025.",
"Não salte o exame porque foi instalado um controlador novo.",
"Exame aprofundado",
"De 6 em 6 meses para elevadores de passageiros",
"O LOLER exige o exame aprofundado de equipamentos de elevação para elevar pessoas, tipicamente com intervalos de seis meses, por uma pessoa competente, com relatórios para o responsável.",
"Um par de olhos que não são os da manutenção, duas vezes por ano. O inversor novo não suspende o diário.",
"Classificação EN 81-80",
"Alto / médio / baixo documentados; datas para os altos",
"A EN 81-80 é a regra para a melhoria de elevadores existentes. Os perigos são identificados e classificados para que os graves sejam tratados primeiro.",
"O que pode matar alguém este ano, o que pode esperar. Uma lista classificada ganha a um vago «vamos modernizar».",
"Acessibilidade (82)",
"Botões, voz, tempos de porta, mobiliário da cabina conforme a caixa permitir",
"A EN 81-82 abrange melhorias de acessibilidade em elevadores existentes. Algumas características da 70 cabem; outras precisam de uma cabina nova.",
"Muitas vezes pode baixar um COP e abrandar as portas. Nem sempre pode fazer crescer uma porta de 800 mm até 900 mm. Escreva o que a caixa aceita de facto.",
"Comportamento em caso de incêndio",
"Recolha se o controlador conseguir; caso contrário, um plano humano",
"Acrescentar uma recolha ao estilo da EN 81-73 a um controlador existente é por vezes possível. O comportamento de evacuação da EN 81-76 é uma especificação de elevador novo.",
"Pode conseguir ensinar uma cabina antiga a estacionar. Não a consegue ensinar a continuar a funcionar como uma cabina 76. Isso é uma substituição.",
"Atualize para EN 81-28 bidirecional se ainda for uma campainha",
"O alarme remoto segundo a EN 81-28 é uma melhoria 80 habitual e uma constatação frequente de exame em cabinas mais antigas.",
"Se o «alarme» ainda fizer tocar um armário, isso é um item de classificação, não um traço de personalidade do edifício.",
"Ocupação do átrio",
"Primeiras portas",
"Parceiro principal",
"Cada visitante, cada sessão",
"Capa e patamar — a primeira coisa que quem especifica vê.",
"Fabricantes de elevadores, grandes empreiteiros, organismos notificados.",
"Arte horizontal 16:9, título de 8 palavras, linha de 20 palavras, uma ligação.",
"Piso em destaque",
"Depois da lição",
"Parceiro das normas",
"Quem termina um piso",
"Fica sob «piso concluído» na EN 81-76, 72, 73 e no LOLER.",
"Fabricantes de elevadores de evacuação, gabinetes de estratégia de incêndio, especialistas em acessibilidade.",
"Marca quadrada, afirmação de 6 palavras, apoio de 16 palavras, uma ligação.",
"Faixa da biblioteca de normas",
"Enquanto navegam",
"Responsáveis a consultar uma parte",
]
