/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertsRouteImport } from './routes/adverts'
import { Route as AsmeRouteImport } from './routes/asme'
import { Route as ClassifyRouteImport } from './routes/classify'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as TestRouteImport } from './routes/test'
import { Route as UkRouteImport } from './routes/uk'
import { Route as WorldRouteImport } from './routes/world'
import { Route as AdvertsIndexRouteImport } from './routes/adverts.index'
import { Route as AdvertsIdRouteImport } from './routes/adverts.$id'
import { Route as AsmeIndexRouteImport } from './routes/asme.index'
import { Route as AsmeLearnRouteImport } from './routes/asme.learn'
import { Route as AsmeLibraryRouteImport } from './routes/asme.library'
import { Route as AsmePracticeRouteImport } from './routes/asme.practice'
import { Route as AsmeTestRouteImport } from './routes/asme.test'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnIdRouteImport } from './routes/learn.$id'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios.index'
import { Route as ScenariosIdRouteImport } from './routes/scenarios.$id'
import { Route as SpecsIndexRouteImport } from './routes/specs.index'
import { Route as SpecsIdRouteImport } from './routes/specs.$id'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors.index'
import { Route as SponsorsIdRouteImport } from './routes/sponsors.$id'
import { Route as AsmeLearnIndexRouteImport } from './routes/asme.learn.index'
import { Route as AsmeLearnIdRouteImport } from './routes/asme.learn.$id'
import { Route as AsmeLibraryIndexRouteImport } from './routes/asme.library.index'
import { Route as AsmeLibraryIdRouteImport } from './routes/asme.library.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertsRoute = AdvertsRouteImport.update({
  id: '/adverts',
  path: '/adverts',
  getParentRoute: () => rootRouteImport,
} as any)
const AsmeRoute = AsmeRouteImport.update({
  id: '/asme',
  path: '/asme',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyRoute = ClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const UkRoute = UkRouteImport.update({
  id: '/uk',
  path: '/uk',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertsIndexRoute = AdvertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvertsRoute,
} as any)
const AdvertsIdRoute = AdvertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdvertsRoute,
} as any)
const AsmeIndexRoute = AsmeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AsmeRoute,
} as any)
const AsmeLearnRoute = AsmeLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AsmeRoute,
} as any)
const AsmeLibraryRoute = AsmeLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AsmeRoute,
} as any)
const AsmePracticeRoute = AsmePracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AsmeRoute,
} as any)
const AsmeTestRoute = AsmeTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AsmeRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnIdRoute = LearnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LearnRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScenariosRoute,
} as any)
const ScenariosIdRoute = ScenariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ScenariosRoute,
} as any)
const SpecsIndexRoute = SpecsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecsRoute,
} as any)
const SpecsIdRoute = SpecsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpecsRoute,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SponsorsRoute,
} as any)
const SponsorsIdRoute = SponsorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SponsorsRoute,
} as any)
const AsmeLearnIndexRoute = AsmeLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AsmeLearnRoute,
} as any)
const AsmeLearnIdRoute = AsmeLearnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AsmeLearnRoute,
} as any)
const AsmeLibraryIndexRoute = AsmeLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AsmeLibraryRoute,
} as any)
const AsmeLibraryIdRoute = AsmeLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AsmeLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adverts': typeof AdvertsRouteWithChildren
  '/asme': typeof AsmeRouteWithChildren
  '/classify': typeof ClassifyRoute
  '/drill': typeof DrillRoute
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/scenarios': typeof ScenariosRouteWithChildren
  '/shop': typeof ShopRoute
  '/specs': typeof SpecsRouteWithChildren
  '/sponsors': typeof SponsorsRouteWithChildren
  '/test': typeof TestRoute
  '/uk': typeof UkRoute
  '/world': typeof WorldRoute
  '/adverts/$id': typeof AdvertsIdRoute
  '/asme/learn': typeof AsmeLearnRouteWithChildren
  '/asme/library': typeof AsmeLibraryRouteWithChildren
  '/asme/practice': typeof AsmePracticeRoute
  '/asme/test': typeof AsmeTestRoute
  '/learn/$id': typeof LearnIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/sponsors/$id': typeof SponsorsIdRoute
  '/adverts/': typeof AdvertsIndexRoute
  '/asme/': typeof AsmeIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/asme/learn/$id': typeof AsmeLearnIdRoute
  '/asme/library/$id': typeof AsmeLibraryIdRoute
  '/asme/learn/': typeof AsmeLearnIndexRoute
  '/asme/library/': typeof AsmeLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classify': typeof ClassifyRoute
  '/drill': typeof DrillRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/shop': typeof ShopRoute
  '/test': typeof TestRoute
  '/uk': typeof UkRoute
  '/world': typeof WorldRoute
  '/adverts/$id': typeof AdvertsIdRoute
  '/asme/practice': typeof AsmePracticeRoute
  '/asme/test': typeof AsmeTestRoute
  '/learn/$id': typeof LearnIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/sponsors/$id': typeof SponsorsIdRoute
  '/adverts': typeof AdvertsIndexRoute
  '/asme': typeof AsmeIndexRoute
  '/learn': typeof LearnIndexRoute
  '/library': typeof LibraryIndexRoute
  '/scenarios': typeof ScenariosIndexRoute
  '/specs': typeof SpecsIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/asme/learn/$id': typeof AsmeLearnIdRoute
  '/asme/library/$id': typeof AsmeLibraryIdRoute
  '/asme/learn': typeof AsmeLearnIndexRoute
  '/asme/library': typeof AsmeLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adverts': typeof AdvertsRouteWithChildren
  '/asme': typeof AsmeRouteWithChildren
  '/classify': typeof ClassifyRoute
  '/drill': typeof DrillRoute
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/scenarios': typeof ScenariosRouteWithChildren
  '/shop': typeof ShopRoute
  '/specs': typeof SpecsRouteWithChildren
  '/sponsors': typeof SponsorsRouteWithChildren
  '/test': typeof TestRoute
  '/uk': typeof UkRoute
  '/world': typeof WorldRoute
  '/adverts/$id': typeof AdvertsIdRoute
  '/asme/learn': typeof AsmeLearnRouteWithChildren
  '/asme/library': typeof AsmeLibraryRouteWithChildren
  '/asme/practice': typeof AsmePracticeRoute
  '/asme/test': typeof AsmeTestRoute
  '/learn/$id': typeof LearnIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/specs/$id': typeof SpecsIdRoute
  '/sponsors/$id': typeof SponsorsIdRoute
  '/adverts/': typeof AdvertsIndexRoute
  '/asme/': typeof AsmeIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/scenarios/': typeof ScenariosIndexRoute
  '/specs/': typeof SpecsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/asme/learn/$id': typeof AsmeLearnIdRoute
  '/asme/library/$id': typeof AsmeLibraryIdRoute
  '/asme/learn/': typeof AsmeLearnIndexRoute
  '/asme/library/': typeof AsmeLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adverts'
    | '/asme'
    | '/classify'
    | '/drill'
    | '/learn'
    | '/library'
    | '/placement'
    | '/practice'
    | '/scenarios'
    | '/shop'
    | '/specs'
    | '/sponsors'
    | '/test'
    | '/uk'
    | '/world'
    | '/adverts/$id'
    | '/asme/learn'
    | '/asme/library'
    | '/asme/practice'
    | '/asme/test'
    | '/learn/$id'
    | '/library/$id'
    | '/scenarios/$id'
    | '/specs/$id'
    | '/sponsors/$id'
    | '/adverts/'
    | '/asme/'
    | '/learn/'
    | '/library/'
    | '/scenarios/'
    | '/specs/'
    | '/sponsors/'
    | '/asme/learn/$id'
    | '/asme/library/$id'
    | '/asme/learn/'
    | '/asme/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classify'
    | '/drill'
    | '/placement'
    | '/practice'
    | '/shop'
    | '/test'
    | '/uk'
    | '/world'
    | '/adverts/$id'
    | '/asme/practice'
    | '/asme/test'
    | '/learn/$id'
    | '/library/$id'
    | '/scenarios/$id'
    | '/specs/$id'
    | '/sponsors/$id'
    | '/adverts'
    | '/asme'
    | '/learn'
    | '/library'
    | '/scenarios'
    | '/specs'
    | '/sponsors'
    | '/asme/learn/$id'
    | '/asme/library/$id'
    | '/asme/learn'
    | '/asme/library'
  id:
    | '__root__'
    | '/'
    | '/adverts'
    | '/asme'
    | '/classify'
    | '/drill'
    | '/learn'
    | '/library'
    | '/placement'
    | '/practice'
    | '/scenarios'
    | '/shop'
    | '/specs'
    | '/sponsors'
    | '/test'
    | '/uk'
    | '/world'
    | '/adverts/$id'
    | '/asme/learn'
    | '/asme/library'
    | '/asme/practice'
    | '/asme/test'
    | '/learn/$id'
    | '/library/$id'
    | '/scenarios/$id'
    | '/specs/$id'
    | '/sponsors/$id'
    | '/adverts/'
    | '/asme/'
    | '/learn/'
    | '/library/'
    | '/scenarios/'
    | '/specs/'
    | '/sponsors/'
    | '/asme/learn/$id'
    | '/asme/library/$id'
    | '/asme/learn/'
    | '/asme/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertsRoute: typeof AdvertsRouteWithChildren
  AsmeRoute: typeof AsmeRouteWithChildren
  ClassifyRoute: typeof ClassifyRoute
  DrillRoute: typeof DrillRoute
  LearnRoute: typeof LearnRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  PlacementRoute: typeof PlacementRoute
  PracticeRoute: typeof PracticeRoute
  ScenariosRoute: typeof ScenariosRouteWithChildren
  ShopRoute: typeof ShopRoute
  SpecsRoute: typeof SpecsRouteWithChildren
  SponsorsRoute: typeof SponsorsRouteWithChildren
  TestRoute: typeof TestRoute
  UkRoute: typeof UkRoute
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adverts': {
      id: '/adverts'
      path: '/adverts'
      fullPath: '/adverts'
      preLoaderRoute: typeof AdvertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asme': {
      id: '/asme'
      path: '/asme'
      fullPath: '/asme'
      preLoaderRoute: typeof AsmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify': {
      id: '/classify'
      path: '/classify'
      fullPath: '/classify'
      preLoaderRoute: typeof ClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uk': {
      id: '/uk'
      path: '/uk'
      fullPath: '/uk'
      preLoaderRoute: typeof UkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adverts/': {
      id: '/adverts/'
      path: '/'
      fullPath: '/adverts/'
      preLoaderRoute: typeof AdvertsIndexRouteImport
      parentRoute: typeof AdvertsRoute
    }
    '/adverts/$id': {
      id: '/adverts/$id'
      path: '/$id'
      fullPath: '/adverts/$id'
      preLoaderRoute: typeof AdvertsIdRouteImport
      parentRoute: typeof AdvertsRoute
    }
    '/asme/': {
      id: '/asme/'
      path: '/'
      fullPath: '/asme/'
      preLoaderRoute: typeof AsmeIndexRouteImport
      parentRoute: typeof AsmeRoute
    }
    '/asme/learn': {
      id: '/asme/learn'
      path: '/learn'
      fullPath: '/asme/learn'
      preLoaderRoute: typeof AsmeLearnRouteImport
      parentRoute: typeof AsmeRoute
    }
    '/asme/library': {
      id: '/asme/library'
      path: '/library'
      fullPath: '/asme/library'
      preLoaderRoute: typeof AsmeLibraryRouteImport
      parentRoute: typeof AsmeRoute
    }
    '/asme/practice': {
      id: '/asme/practice'
      path: '/practice'
      fullPath: '/asme/practice'
      preLoaderRoute: typeof AsmePracticeRouteImport
      parentRoute: typeof AsmeRoute
    }
    '/asme/test': {
      id: '/asme/test'
      path: '/test'
      fullPath: '/asme/test'
      preLoaderRoute: typeof AsmeTestRouteImport
      parentRoute: typeof AsmeRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$id': {
      id: '/learn/$id'
      path: '/$id'
      fullPath: '/learn/$id'
      preLoaderRoute: typeof LearnIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/scenarios/$id': {
      id: '/scenarios/$id'
      path: '/$id'
      fullPath: '/scenarios/$id'
      preLoaderRoute: typeof ScenariosIdRouteImport
      parentRoute: typeof ScenariosRoute
    }
    '/specs/': {
      id: '/specs/'
      path: '/'
      fullPath: '/specs/'
      preLoaderRoute: typeof SpecsIndexRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/specs/$id': {
      id: '/specs/$id'
      path: '/$id'
      fullPath: '/specs/$id'
      preLoaderRoute: typeof SpecsIdRouteImport
      parentRoute: typeof SpecsRoute
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/sponsors/$id': {
      id: '/sponsors/$id'
      path: '/$id'
      fullPath: '/sponsors/$id'
      preLoaderRoute: typeof SponsorsIdRouteImport
      parentRoute: typeof SponsorsRoute
    }
    '/asme/learn/': {
      id: '/asme/learn/'
      path: '/'
      fullPath: '/asme/learn/'
      preLoaderRoute: typeof AsmeLearnIndexRouteImport
      parentRoute: typeof AsmeLearnRoute
    }
    '/asme/learn/$id': {
      id: '/asme/learn/$id'
      path: '/$id'
      fullPath: '/asme/learn/$id'
      preLoaderRoute: typeof AsmeLearnIdRouteImport
      parentRoute: typeof AsmeLearnRoute
    }
    '/asme/library/': {
      id: '/asme/library/'
      path: '/'
      fullPath: '/asme/library/'
      preLoaderRoute: typeof AsmeLibraryIndexRouteImport
      parentRoute: typeof AsmeLibraryRoute
    }
    '/asme/library/$id': {
      id: '/asme/library/$id'
      path: '/$id'
      fullPath: '/asme/library/$id'
      preLoaderRoute: typeof AsmeLibraryIdRouteImport
      parentRoute: typeof AsmeLibraryRoute
    }
  }
}

interface AdvertsRouteChildren {
  AdvertsIdRoute: typeof AdvertsIdRoute
  AdvertsIndexRoute: typeof AdvertsIndexRoute
}

const AdvertsRouteChildren: AdvertsRouteChildren = {
  AdvertsIdRoute: AdvertsIdRoute,
  AdvertsIndexRoute: AdvertsIndexRoute,
}

const AdvertsRouteWithChildren =
  AdvertsRoute._addFileChildren(AdvertsRouteChildren)

interface AsmeLearnRouteChildren {
  AsmeLearnIdRoute: typeof AsmeLearnIdRoute
  AsmeLearnIndexRoute: typeof AsmeLearnIndexRoute
}

const AsmeLearnRouteChildren: AsmeLearnRouteChildren = {
  AsmeLearnIdRoute: AsmeLearnIdRoute,
  AsmeLearnIndexRoute: AsmeLearnIndexRoute,
}

const AsmeLearnRouteWithChildren = AsmeLearnRoute._addFileChildren(
  AsmeLearnRouteChildren,
)

interface AsmeLibraryRouteChildren {
  AsmeLibraryIdRoute: typeof AsmeLibraryIdRoute
  AsmeLibraryIndexRoute: typeof AsmeLibraryIndexRoute
}

const AsmeLibraryRouteChildren: AsmeLibraryRouteChildren = {
  AsmeLibraryIdRoute: AsmeLibraryIdRoute,
  AsmeLibraryIndexRoute: AsmeLibraryIndexRoute,
}

const AsmeLibraryRouteWithChildren = AsmeLibraryRoute._addFileChildren(
  AsmeLibraryRouteChildren,
)

interface AsmeRouteChildren {
  AsmeLearnRoute: typeof AsmeLearnRouteWithChildren
  AsmeLibraryRoute: typeof AsmeLibraryRouteWithChildren
  AsmePracticeRoute: typeof AsmePracticeRoute
  AsmeTestRoute: typeof AsmeTestRoute
  AsmeIndexRoute: typeof AsmeIndexRoute
}

const AsmeRouteChildren: AsmeRouteChildren = {
  AsmeLearnRoute: AsmeLearnRouteWithChildren,
  AsmeLibraryRoute: AsmeLibraryRouteWithChildren,
  AsmePracticeRoute: AsmePracticeRoute,
  AsmeTestRoute: AsmeTestRoute,
  AsmeIndexRoute: AsmeIndexRoute,
}

const AsmeRouteWithChildren = AsmeRoute._addFileChildren(AsmeRouteChildren)

interface LearnRouteChildren {
  LearnIdRoute: typeof LearnIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnIdRoute: LearnIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface ScenariosRouteChildren {
  ScenariosIdRoute: typeof ScenariosIdRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

const ScenariosRouteChildren: ScenariosRouteChildren = {
  ScenariosIdRoute: ScenariosIdRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}

const ScenariosRouteWithChildren = ScenariosRoute._addFileChildren(
  ScenariosRouteChildren,
)

interface SpecsRouteChildren {
  SpecsIdRoute: typeof SpecsIdRoute
  SpecsIndexRoute: typeof SpecsIndexRoute
}

const SpecsRouteChildren: SpecsRouteChildren = {
  SpecsIdRoute: SpecsIdRoute,
  SpecsIndexRoute: SpecsIndexRoute,
}

const SpecsRouteWithChildren = SpecsRoute._addFileChildren(SpecsRouteChildren)

interface SponsorsRouteChildren {
  SponsorsIdRoute: typeof SponsorsIdRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
}

const SponsorsRouteChildren: SponsorsRouteChildren = {
  SponsorsIdRoute: SponsorsIdRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
}

const SponsorsRouteWithChildren = SponsorsRoute._addFileChildren(
  SponsorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertsRoute: AdvertsRouteWithChildren,
  AsmeRoute: AsmeRouteWithChildren,
  ClassifyRoute: ClassifyRoute,
  DrillRoute: DrillRoute,
  LearnRoute: LearnRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  PlacementRoute: PlacementRoute,
  PracticeRoute: PracticeRoute,
  ScenariosRoute: ScenariosRouteWithChildren,
  ShopRoute: ShopRoute,
  SpecsRoute: SpecsRouteWithChildren,
  SponsorsRoute: SponsorsRouteWithChildren,
  TestRoute: TestRoute,
  UkRoute: UkRoute,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
